# Generated by Django 3.2 on 2021-07-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['customer'], 'verbose_name': 'Order'},
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='brahianocampo7@gmail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
